import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { useUser } from "@clerk/nextjs";
import { SignInButton, SignOutButton } from "@clerk/clerk-react";

const Home: NextPage = () => {

  const res = api.example.getAll.useQuery();

  console.log(res);

  const user = useUser();

  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1>HI</h1>

          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}         
          <p className="text-2xl text-white">
            {/* {res.data ? res.data.title : "Loading tRPC query..."} */}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
